### PR TITLE
CLI increments to search based on both name and description of the

### PR DESCRIPTION
**Pull request by isandesh1986**
templates #1170

Adresses/Fixes #<ISSUENO>.

Implements

* 
* 
* 

@devonfw/cobigen

### CODE REVIEW

**Comment by maybeec** [comment]
Thanks for the new pr, looks fine. Could you please adapt the documentation accordingly?

**Comment by maybeec** [comment]
I think you have to remove the threshold test on equals comparison. Otherwise, generation will even start for similar but not equal strings. Am I right?

**Comment by isandesh1986** [comment]
> I think you have to remove the threshold test on equals comparison. Otherwise, generation will even start for similar but not equal strings. Am I right?

Right. My bad! I missed to remove it. Have taken care now. Kindly check.

**Comment by isandesh1986** [comment]
> Thanks for the new pr, looks fine. Could you please adapt the documentation accordingly?

Documentation also has been updated. Thanks

**Pull request merged**
