### PR TITLE
Fix for template generation issue 1161

### LINKED ISSUE #1161: Cobigen failed to generate code after doing adapt templates and updating templates
### Expected behavior

Expected to generate code for the selected resources after adapting and updating templates. 

### Actual behavior

Fails with the below error mentioned in the comment

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  create an entity class as mentioned below
2.  right click -> cobigen -> adapt templates -> generate .

### Comments/Hints:
##Input:
public class EmployeeEntity {
  private String name;
  private Integer age;
  private String location;
}

##Selected Resources:
1. CRUD Rest service
2. CRUD SpringData Repository
3. CRUD UC logic
4. Entity Infrastructure
5. TOs

### Affected version:
* devon-ide version: 2020.04.001
* OS: Windows
* Browser: Chrome

### PR DESCRIPTION
**Pull request by isandesh1986**
Adresses/Fixes #1161 .

Implements

Fix for template generation issue 1161
* 
* 

@devonfw/cobigen

### CODE REVIEW

**Comment by maybeec** [comment]
Hi Sandesh, be careful as you are changing the logic of the method from testing for full qualified type names to simple type names. Other templates will call this method with the full qualified name and they will fail afterwards.
Couldn't you simply call the method with the full qualified name from the template?

**Comment by isandesh1986** [comment]
> Hi @isandesh1986 , be careful as you are changing the logic of the method from testing for full qualified type names to simple type names. Other templates will call this method with the full qualified name and they will fail afterwards.
> Couldn't you simply call the method with the full qualified name from the template?

Hi @maybeec , All the templates are passing fully qualified type name as string "javax.persistence.EmbeddedId". So we should be good. Let me know.

**Comment by maybeec** [comment]
There seem to be 6 template tests failing. Could you check for the reason?

**Comment by maybeec** [comment]
closing in favor of fix done in d24d6aa00a7f4a9ea90303a1d35086ba2991ca0f
The fix in the PR circumvents class loading, but actually the issue was, that the class was not in classpath

**Pull request closed without merging**
