### PR TITLE
Feature/test ci

### PR DESCRIPTION
**Pull request by hohwille**
Improves a simple JUnit test method I was hitting and is used to see/verify if `dev_core` or CI in general is broken.

Implements

* Improved test with AssertJ

@devonfw/cobigen

### CODE REVIEW

**Comment by hohwille** [comment]
As I guessed CI is giving the same result as with PR #1067.
So either the branch `dev_core` or the CI itself is broken.
```
Failed tests: 

  TemplatesConfigurationReaderTest.testExceptionMessageForDuplicateTemplateNames:495 

Expecting:

 <"file:///home/pl/slave-1/workspace/cobigen_cobigen_PR-1068-merge/cobigen/cobigen-core-parent/cobigen-core/src/test/resources/testdata/unittest/config/reader/TemplatesConfigurationReaderTest/faulty_duplicate_scanned_id/templates.xml:

Could not parse configuration file:

">

to contain:

 <"Bar"> 

  TemplateConfigurationUpgraderTest.testCorrectUpgrade_v1_2_TO_v2_1:51 [Source Version] expected:<v1.2> but was:<null>

  TemplateConfigurationUpgraderTest.testCorrectV2_1SchemaDetection:80 expected:<v4.0> but was:<null>

  ContextConfigurationUpgraderTest.testCorrectV2_1SchemaDetection:80 expected:<v2.1> but was:<null>

  ContextConfigurationUpgraderTest.testCorrectUpgrade_v2_0_TO_v2_1:51 [Source Version] expected:<v2.0> but was:<null>


Tests in error: 

  TemplatesConfigurationReaderTest.testRelocate_overlappingExplicitTemplateDestinationPathAndRelocatedScanPath:547 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplateScanDoesNotOverwriteExplicitTemplateDeclarations:128 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testIncrementRefOutsideCurrentFile:411 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testEmptyTemplateExtensionDeclarationDoesNotOverrideAnyDefaults:208 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplatesOfAPackageRetrieval:54 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate_overlappingTemplateExtensionAndScan:508 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplateScan:74 » InvalidConfiguration fi...

  TemplatesConfigurationReaderTest.testTemplateRefOutsideCurrentFile:377 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplateExtensionDeclarationOverridesTemplateScanDefaults:164 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate:651 » InvalidConfiguration file:...

  TemplatesConfigurationReaderTest.testIncrementComposition_combiningAllPossibleReferences:342 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate_withTemplateFilenameEnding:613 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testCorrectResolutionOfTemplateScanReferences:291 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate_propertiesResolution:582 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplatesSourceFolder:98 » InvalidConfiguration

  HealthCheckTest.testFailingUpgradeContextConfigurationWithNoTemplatesConfig:193 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeContextConfigurationWithNoTemplatesConfig:72 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeTemplatesConfiguration:116 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeAll:137 » InvalidConfiguration file:///tm...

  HealthCheckTest.testSuccessfulUpgradeContextConfigurationWithTwoTemplateConfigs:95 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeContextConfiguration:50 » InvalidConfiguration


Tests run: 58, Failures: 5, Errors: 21, Skipped: 0
```

**Comment by jdiazgon** [comment]
Most probably those tests are failing since we migrated CobiGen from Java 8 to Java 11.

**Comment by hohwille** [comment]
Thanks for the feedback @jdiazgon 
It seems that currently nobody is really in charge for CobiGen.
I would love to follow a strict CI process in all repositories of our official `devonfw` organisation.
Wont know if I will find some time to assist here and I might also not be able to solve all issues (esp. when it comes to eclipse/p2 specific problems)...

**Comment by hohwille** [comment]
Any chance we can get CI for cobigen working again? I can revert the pom change from this PR that was not indented in case that matters.

**Comment by hohwille** [comment]
Actually where does that POM change come from. This is my only commit for this PR:
https://github.com/devonfw/cobigen/pull/1068/commits/14bee61a18c1009ab882b6b5e618f802142fbf8e

Apart from that I only merged with master.

**Comment by hohwille** [comment]
OK, my local git fork clone for that feature branch did not contain the change. Again kind of a bug in git... However, I forced a change of this "ghost change" and now this PR should be clean again: just a trivial change in a JUnit with a small improvement. If build is still failing (as expected) CI is broken and CobiGen is in trouble.

**Comment by hohwille** [comment]
FYI: You should IMHO also switch to travis rather than this proprietary closed production-line build. CobiGen is OSS for a long time. It should therefore be open.

**Comment by jdiazgon** [comment]
> FYI: You should IMHO also switch to travis rather than this proprietary closed production-line build. CobiGen is OSS for a long time. It should therefore be open.

Totally agree. Unfortunately we do not have much free time to fix the CI, so I can not give you a date of when this will be fixed.

**Pull request merged**
