### PR TITLE
#1548 SearchCriteriaTo generated in wrong package.

### PR DESCRIPTION
**Pull request by ZakariaeMkassi**
#1548 devon4j templates: SearchCriteriaTo generated in wrong package. 
it was simply done : the SearchCriteriaTo object was moved from the wrong package logic to common to follow the layered architecture. In addition, all places where the object is imported have been adjusted

### CODE REVIEW

**Review by EduardKrieger — APPROVED** [review]

**Review by mdukhan — APPROVED** [review]

**Comment by mdukhan** [comment]
Should the changes be merged to master? or the feature branch?

**Comment by ZakariaeMkassi** [comment]
I'm not sure where to merge the changes. We will ask Malte next week.

**Review by Zylesto — APPROVED** [review]

**Comment by jan-vcapgemini** [comment]
I think we need to provide a test which checks against the specification e.g. compliant code too.

**Review by jan-vcapgemini — APPROVED** [review]

**Review by Zylesto — APPROVED** [review]

**Comment by jan-vcapgemini** [comment]
> I think we need to provide a test which checks against the specification e.g. compliant code generation too.

After discussion, we decided that we should just do a manual test instead.

**Review by NelsonNew — APPROVED** [review]

**Review by KHucklenbroich — APPROVED** [review]

**Review by maybeec — APPROVED** [review]

**Pull request merged**
