### PR TITLE
Update mgmt_ide-setup.asciidoc

### PR DESCRIPTION
**Pull request by jan-vcapgemini**
Updated IDE setup steps with new workarounds because of problems with latest devonfw version.

@devonfw/cobigen

### CODE REVIEW

**Review by EduardKrieger — COMMENTED** [review]
Cause of the problems with the new devonfw-ide releases, we talked about not using the latest version for this guide and use an older and already tested version. We will have to update this guide after testing every release than.

**Review by maybeec — DISMISSED** [review]

**Comment by maybeec** [comment]
Spellcheck fails: 

```
 <context> documentation/mgmt_ide-setup.asciidoc
--------------------------------------------------------------------------------
cobigen
eclipsepde
freemarker
longpaths
swtbot
url
--------------------------------------------------------------------------------

!!!Spelling check failed!!!
```

Please comply to the typography of the words as represented in our dict: https://github.com/devonfw/.github/blob/master/en-devonfw.dict

**Review by maybeec — CHANGES_REQUESTED** [review]
Please correct spelling

**Comment by maybeec** [comment]
I think you updated the docs into even more faulty typo. Have a look what I wrote ;)

**Comment by jan-vcapgemini** [comment]
spellcheck bugged?

**Review by maybeec — APPROVED** [review]

**Pull request merged**
