### PR TITLE
Feature/158 lat variables syntax

### PR DESCRIPTION
**Pull request by hohwille**
Adresses #158.

Implements

* change "underscore/case syntax" to align with language-agnostic templates

Please note that `X_«var»_X` was still not sufficient in case `«var»` is containing `_X` itself as e.g. `X_MY_XTENDED_PROPERTY_X` because here we can not determine if the variable expression is `X_MY_X` (resolve `My` in CapitalCase) or `X_MY_XETENDED_PROPERTY_X` (resolve `MyXtendedProperty` in CapitalCaseWithUnderscores).

@devonfw/cobigen

### CODE REVIEW

**Comment by hohwille** [comment]
Jenkins failed:
```
Results :


Failed tests: 

  TemplatesConfigurationReaderTest.testExceptionMessageForDuplicateTemplateNames:495 null

  ContextConfigurationUpgraderTest.testCorrectV2_1SchemaDetection:80 expected:<v2.1> but was:<null>

  ContextConfigurationUpgraderTest.testCorrectUpgrade_v2_0_TO_v2_1:51 [Source Version] expected:<v2.0> but was:<null>

  TemplateConfigurationUpgraderTest.testCorrectUpgrade_v1_2_TO_v2_1:51 [Source Version] expected:<v1.2> but was:<null>

  TemplateConfigurationUpgraderTest.testCorrectV2_1SchemaDetection:80 expected:<v4.0> but was:<null>


Tests in error: 

  TemplatesConfigurationReaderTest.testRelocate_overlappingExplicitTemplateDestinationPathAndRelocatedScanPath:547 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplateScanDoesNotOverwriteExplicitTemplateDeclarations:128 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testIncrementRefOutsideCurrentFile:411 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testEmptyTemplateExtensionDeclarationDoesNotOverrideAnyDefaults:208 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplatesOfAPackageRetrieval:54 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate_overlappingTemplateExtensionAndScan:508 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplateScan:74 » InvalidConfiguration fi...

  TemplatesConfigurationReaderTest.testTemplateRefOutsideCurrentFile:377 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplateExtensionDeclarationOverridesTemplateScanDefaults:164 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate:651 » InvalidConfiguration file:...

  TemplatesConfigurationReaderTest.testIncrementComposition_combiningAllPossibleReferences:342 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate_withTemplateFilenameEnding:613 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testCorrectResolutionOfTemplateScanReferences:291 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testRelocate_propertiesResolution:582 » InvalidConfiguration

  TemplatesConfigurationReaderTest.testTemplatesSourceFolder:98 » InvalidConfiguration

  HealthCheckTest.testFailingUpgradeContextConfigurationWithNoTemplatesConfig:193 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeContextConfigurationWithNoTemplatesConfig:72 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeTemplatesConfiguration:116 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeAll:137 » InvalidConfiguration file:///tm...

  HealthCheckTest.testSuccessfulUpgradeContextConfigurationWithTwoTemplateConfigs:95 » InvalidConfiguration

  HealthCheckTest.testSuccessfulUpgradeContextConfiguration:50 » InvalidConfiguration


Tests run: 58, Failures: 5, Errors: 21, Skipped: 0
```

**Comment by hohwille** [comment]
Side-note:
```
    public void testExceptionMessageForDuplicateTemplateNames() {
        String message = "";
        try {
            testErrorOnDuplicateScannedIds();
            fail("An Exception should have been thrown");
        } catch (Exception e) {
            message = e.getMessage();
        }
        assertFalse(message.indexOf("Bar") == -1);
    }
```

This `assertFalse(message.indexOf("Bar") == -1)` looks really odd to me.

**Comment by hohwille** [comment]
OK, I checked out `dev_core` and get the same errors.
So if the build of the project itself does not work, it seems impossible to contriubte with quality following our PR processes. Get your CI working in CobiGen and then I come back to start my work providing PRs for new features.

**Comment by maybeec** [comment]
I checked the formatting, seems to be fine anyhow. The diff was misleading.

**Pull request merged**
